services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rfcam
      POSTGRES_PASSWORD: "R1RXDw6sH2zS_oQ7ZWv15BQ46Vs9RFha"
    volumes:
      - rfcam_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "hMvlusrFEebMSDB0XP-kO1Tym0svNEp4"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: rfcam_test
      POSTGRES_PASSWORD: "oFmnMkh9s2YEnncHQnrWrMWNOnV_MUmC"
    volumes:
      - rfcam_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "rd_kg5Dfm-ddA5QSIPJUTaxGGoSAqjO7"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  rfcam_data:
  rfcam_test_data:
